######################################################################
# Automatically generated by qmake (2.01a) Wed May 22 17:35:50 2013
######################################################################

TEMPLATE = app
TARGET = 
#DEPENDPATH += . GeneratedFiles
#INCLUDEPATH += . GeneratedFiles

# Input
HEADERS += keyboard.h login.h \
    inputmethod.h \
    formhanzitable.h \
    HanziManager.h \
    formnumpad.h \
    padbase.h \
    formsymbolpad.h \
    formhanziselector.h \
    ChineseTranslator.h \
    dialogtooltip.h

FORMS += keyboard.ui \
    formhanzitable.ui \
    formnumpad.ui \
    formsymbolpad.ui \
    formhanziselector.ui \
    dialogtooltip.ui

SOURCES += keyboard.cpp \
           login.cpp \
           main.cpp \
           inputmethod.cpp \
    formhanzitable.cpp \
    HanziManager.cpp \
    formnumpad.cpp \
    padbase.cpp \
    formsymbolpad.cpp \
    formhanziselector.cpp \
    dialogtooltip.cpp

RESOURCES += keypad.qrc

#linux-g++ {
#    QMAKE_CXXFLAGS += -std=C++0x
#}
